Queremos aprender un modelo de clasificación binario capaz de predecir si va a llover mañana, a partir de datos observables el día anterior.

### 1. Preparación del dataset

In [69]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
import sklearn

from pandas import Series, DataFrame
from pylab import rcParams
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics 
from sklearn.metrics import classification_report
dataset=pd.read_csv("datos/meteo.csv")
dataset[:100]
#primero visualizamos el dataset para ver que campos vamos  a utilizar

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0.0,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0.0,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,0.0,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,1.0,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,0.2,No
5,2008-12-06,Albury,14.6,29.7,0.2,NaN,NaN,WNW,56.0,W,...,23.0,1009.2,1005.4,NaN,NaN,20.6,28.9,No,0.0,No
6,2008-12-07,Albury,14.3,25.0,0.0,NaN,NaN,W,50.0,SW,...,19.0,1009.6,1008.2,1.0,NaN,18.1,24.6,No,0.0,No
7,2008-12-08,Albury,7.7,26.7,0.0,NaN,NaN,W,35.0,SSE,...,19.0,1013.4,1010.1,NaN,NaN,16.3,25.5,No,0.0,No
8,2008-12-09,Albury,9.7,31.9,0.0,NaN,NaN,NNW,80.0,SE,...,9.0,1008.9,1003.6,NaN,NaN,18.3,30.2,No,1.4,Yes
9,2008-12-10,Albury,13.1,30.1,1.4,NaN,NaN,W,28.0,S,...,27.0,1007.0,1005.7,NaN,NaN,20.1,28.2,Yes,0.0,No
10,2008-12-11,Albury,13.4,30.4,0.0,NaN,NaN,N,30.0,SSE,...,22.0,1011.8,1008.7,NaN,NaN,20.4,28.8,No,2.2,Yes
11,2008-12-12,Albury,15.9,21.7,2.2,NaN,NaN,NNE,31.0,NE,...,91.0,1010.5,1004.2,8.0,8.0,15.9,17.0,Yes,15.6,Yes
12,2008-12-13,Albury,15.9,18.6,15.6,NaN,NaN,W,61.0,NNW,...,93.0,994.3,993.0,8.0,8.0,17.4,15.8,Yes,3.6,Yes
13,2008-12-14,Albury,12.6,21.0,3.6,NaN,NaN,SW,44.0,W,...,43.0,1001.2,1001.8,NaN,7.0,15.8,19.8,Yes,0.0,No
14,2008-12-16,Albury,9.8,27.7,NaN,NaN,NaN,WNW,50.0,NaN,...,28.0,1013.4,1010.3,0.0,NaN,17.3,26.2,NaN,0.0,No
15,2008-12-17,Albury,14.1,20.9,0.0,NaN,NaN,ENE,22.0,SSW,...,82.0,1012.2,1010.4,8.0,1.0,17.2,18.1,No,16.8,Yes
16,2008-12-18,Albury,13.5,22.9,16.8,NaN,NaN,W,63.0,N,...,65.0,1005.8,1002.2,8.0,1.0,18.0,21.5,Yes,10.6,Yes
17,2008-12-19,Albury,11.2,22.5,10.6,NaN,NaN,SSE,43.0,WSW,...,32.0,1009.4,1009.7,NaN,2.0,15.5,21.0,Yes,0.0,No
18,2008-12-20,Albury,9.8,25.6,0.0,NaN,NaN,SSE,26.0,SE,...,26.0,1019.2,1017.1,NaN,NaN,15.8,23.2,No,0.0,No
19,2008-12-21,Albury,11.5,29.3,0.0,NaN,NaN,S,24.0,SE,...,28.0,1019.3,1014.8,NaN,NaN,19.1,27.3,No,0.0,No
20,2008-12-22,Albury,17.1,33.0,0.0,NaN,NaN,NE,43.0,NE,...,28.0,1013.6,1008.1,NaN,1.0,24.5,31.6,No,0.0,No
21,2008-12-23,Albury,20.5,31.8,0.0,NaN,NaN,WNW,41.0,W,...,24.0,1007.8,1005.7,NaN,NaN,23.8,30.8,No,0.0,No
22,2008-12-24,Albury,15.3,30.9,0.0,NaN,NaN,N,33.0,ESE,...,23.0,1011.0,1008.2,5.0,NaN,20.9,29.0,No,0.0,No
23,2008-12-25,Albury,12.6,32.4,0.0,NaN,NaN,W,43.0,E,...,17.0,1012.9,1010.1,NaN,NaN,21.5,31.2,No,0.0,No
24,2008-12-26,Albury,16.2,33.9,0.0,NaN,NaN,WSW,35.0,SE,...,19.0,1010.9,1007.6,NaN,1.0,23.2,33.0,No,0.0,No
25,2008-12-27,Albury,16.9,33.0,0.0,NaN,NaN,WSW,57.0,NaN,...,28.0,1006.8,1003.6,NaN,1.0,26.6,31.2,No,0.0,No
26,2008-12-28,Albury,20.1,32.7,0.0,NaN,NaN,WNW,48.0,N,...,15.0,1005.2,1001.7,NaN,NaN,24.6,32.1,No,0.0,No
27,2008-12-29,Albury,19.7,27.2,0.0,NaN,NaN,WNW,46.0,NW,...,22.0,1004.8,1004.2,NaN,NaN,21.6,26.1,No,1.2,Yes
28,2008-12-30,Albury,12.5,24.2,1.2,NaN,NaN,WNW,50.0,WSW,...,70.0,1005.6,1003.4,8.0,8.0,12.5,18.2,Yes,0.8,No
29,2008-12-31,Albury,12.0,24.4,0.8,NaN,NaN,W,39.0,WNW,...,28.0,1006.1,1005.1,1.0,NaN,16.9,22.7,No,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2009-02-10,Albury,14.9,27.3,0.0,NaN,NaN,SSE,41.0,SSE,...,30.0,1011.6,1008.5,NaN,1.0,17.4,25.8,No,0.0,No
71,2009-02-11,Albury,13.5,26.7,0.0,NaN,NaN,SSE,46.0,SSE,...,24.0,1012.8,1011.1,NaN,NaN,16.7,24.9,No,0.0,No
72,2009-02-12,Albury,16.1,21.6,0.0,NaN,NaN,SE,46.0,SSE,...,69.0,1017.0,1017.3,2.0,8.0,17.0,17.3,No,3.0,Yes
73,2009-02-13,Albury,14.6,29.0,3.0,NaN,NaN,SSE,41.0,SE,...,21.0,1023.3,1019.7,NaN,NaN,18.0,27.6,Yes,0.0,No
74,2009-02-14,Albury,12.4,29.2,0.0,NaN,NaN,NE,39.0,S,...,18.0,1022.5,1016.4,NaN,NaN,18.3,28.5,No,0.0,No
75,2009-02-15,Albury,13.3,31.3,0.0,NaN,NaN,NNE,41.0,SSE,...,23.0,1016.2,1012.8,NaN,NaN,19.2,29.2,No,0.0,No
76,2009-02-16,Albury,17.2,31.1,0.0,NaN,NaN,E,35.0,SE,...,22.0,1017.7,1013.8,NaN,NaN,21.4,29.5,No,0.0,No
77,2009-02-17,Albury,12.5,28.8,0.0,NaN,NaN,N,31.0,SSE,...,17.0,1017.2,1013.5,NaN,NaN,18.0,27.0,No,0.0,No
78,2009-02-18,Albury,18.0,32.0,0.0,NaN,NaN,NW,31.0,ENE,...,22.0,1012.4,1007.5,NaN,NaN,22.1,30.7,No,0.0,No
79,2009-02-19,Albury,16.2,34.0,0.0,NaN,NaN,WSW,48.0,SE,...,16.0,1007.8,1004.5,NaN,NaN,21.0,32.7,No,0.0,No
80,2009-02-20,Albury,18.7,29.1,0.0,NaN,NaN,SSW,41.0,NNW,...,39.0,1010.1,1010.8,NaN,NaN,21.5,26.8,No,0.0,No
81,2009-02-21,Albury,13.7,31.7,0.0,NaN,NaN,SSE,28.0,SSE,...,19.0,1012.5,1010.4,NaN,NaN,19.3,29.8,No,0.0,No
82,2009-02-22,Albury,15.5,33.2,0.0,NaN,NaN,NW,31.0,S,...,23.0,1015.6,1012.4,NaN,NaN,20.9,31.3,No,0.0,No
83,2009-02-23,Albury,14.3,34.0,0.0,NaN,NaN,NW,70.0,SE,...,10.0,1013.0,1009.2,NaN,NaN,20.7,33.4,No,0.0,No
84,2009-02-24,Albury,12.9,29.6,0.0,NaN,NaN,WNW,46.0,SW,...,14.0,1014.0,1012.7,6.0,7.0,18.7,28.6,No,0.0,No
85,2009-02-25,Albury,8.9,31.9,0.0,NaN,NaN,WNW,43.0,NaN,...,16.0,1016.6,1013.4,7.0,7.0,15.0,29.3,No,0.0,No
86,2009-02-26,Albury,15.0,32.7,0.0,NaN,NaN,ESE,26.0,ESE,...,19.0,1017.8,1015.0,NaN,NaN,20.7,30.5,No,0.0,No
87,2009-02-27,Albury,15.4,32.6,0.0,NaN,NaN,W,24.0,NaN,...,25.0,1016.2,1012.6,NaN,NaN,20.0,30.8,No,0.0,No
88,2009-02-28,Albury,16.0,34.5,0.0,NaN,NaN,WSW,44.0,E,...,14.0,1007.5,1004.6,NaN,NaN,22.2,33.6,No,0.0,No
89,2009-03-01,Albury,12.8,30.3,0.0,NaN,NaN,W,30.0,W,...,27.0,1010.5,1008.7,NaN,NaN,17.3,28.1,No,0.0,No
90,2009-03-02,Albury,13.2,31.9,0.0,NaN,NaN,NNW,35.0,S,...,25.0,1014.1,1011.6,NaN,NaN,18.0,29.8,No,0.0,No
91,2009-03-03,Albury,18.0,31.1,0.0,NaN,NaN,WNW,52.0,NE,...,35.0,1014.7,1009.0,5.0,NaN,23.0,29.2,No,0.2,No
92,2009-03-04,Albury,13.8,22.1,0.2,NaN,NaN,WNW,57.0,W,...,26.0,1014.5,1013.1,NaN,NaN,15.6,21.9,No,0.0,No
93,2009-03-05,Albury,11.5,22.0,0.0,NaN,NaN,SW,50.0,WSW,...,33.0,1013.7,1011.8,NaN,NaN,13.9,21.4,No,0.0,No
94,2009-03-06,Albury,7.6,24.0,0.0,NaN,NaN,WSW,30.0,NaN,...,23.0,1014.5,1012.0,NaN,NaN,12.6,22.0,No,0.0,No
95,2009-03-07,Albury,8.3,27.9,0.0,NaN,NaN,W,37.0,S,...,22.0,1015.2,1012.4,NaN,NaN,13.3,27.0,No,0.0,No
96,2009-03-08,Albury,11.0,30.2,0.0,NaN,NaN,SSE,24.0,E,...,20.0,1017.0,1014.7,NaN,NaN,17.6,28.8,No,0.0,No
97,2009-03-09,Albury,13.8,31.8,0.0,NaN,NaN,NNE,24.0,SSE,...,28.0,1019.7,1015.9,NaN,NaN,18.6,30.5,No,0.0,No
98,2009-03-10,Albury,15.5,32.0,0.0,NaN,NaN,NE,50.0,ESE,...,25.0,1019.5,1016.2,NaN,NaN,20.1,30.8,No,1.2,Yes
99,2009-03-11,Albury,18.4,30.5,1.2,NaN,NaN,NE,44.0,NE,...,23.0,1021.3,1018.0,NaN,NaN,21.5,29.6,Yes,0.0,No

In [70]:
dataset.describe()
#usamos una descripcion para saber la media y datos importantes

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RISK_MM
count,141556.000000,141871.000000,140787.000000,81350.000000,74377.000000,132923.000000,140845.000000,139563.000000,140419.000000,138583.000000,128179.000000,128212.000000,88536.000000,85099.000000,141289.000000,139467.000000,142193.000000
mean,12.186400,23.226784,2.349974,5.469824,7.624853,39.984292,14.001988,18.637576,68.843810,51.482606,1017.653758,1015.258204,4.437189,4.503167,16.987509,21.687235,2.360682
std,6.403283,7.117618,8.465173,4.188537,3.781525,13.588801,8.893337,8.803345,19.051293,20.797772,7.105476,7.036677,2.887016,2.720633,6.492838,6.937594,8.477969
min,-8.500000,-4.800000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,980.500000,977.100000,0.000000,0.000000,-7.200000,-5.400000,0.000000
25%,7.600000,17.900000,0.000000,2.600000,4.900000,31.000000,7.000000,13.000000,57.000000,37.000000,1012.900000,1010.400000,1.000000,2.000000,12.300000,16.600000,0.000000
50%,12.000000,22.600000,0.000000,4.800000,8.500000,39.000000,13.000000,19.000000,70.000000,52.000000,1017.600000,1015.200000,5.000000,5.000000,16.700000,21.100000,0.000000
75%,16.800000,28.200000,0.800000,7.400000,10.600000,48.000000,19.000000,24.000000,83.000000,66.000000,1022.400000,1020.000000,7.000000,7.000000,21.600000,26.400000,0.800000
max,33.900000,48.100000,371.000000,145.000000,14.500000,135.000000,130.000000,87.000000,100.000000,100.000000,1041.000000,1039.600000,9.000000,9.000000,40.200000,46.700000,371.000000

In [71]:
dataset.isnull().sum()

Date                 0
Location             0
MinTemp            637
MaxTemp            322
Rainfall          1406
Evaporation      60843
Sunshine         67816
WindGustDir       9330
WindGustSpeed     9270
WindDir9am       10013
WindDir3pm        3778
WindSpeed9am      1348
WindSpeed3pm      2630
Humidity9am       1774
Humidity3pm       3610
Pressure9am      14014
Pressure3pm      13981
Cloud9am         53657
Cloud3pm         57094
Temp9am            904
Temp3pm           2726
RainToday         1406
RISK_MM              0
RainTomorrow         0
dtype: int64

In [72]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142193 entries, 0 to 142192
Data columns (total 24 columns):
Date             142193 non-null object
Location         142193 non-null object
MinTemp          141556 non-null float64
MaxTemp          141871 non-null float64
Rainfall         140787 non-null float64
Evaporation      81350 non-null float64
Sunshine         74377 non-null float64
WindGustDir      132863 non-null object
WindGustSpeed    132923 non-null float64
WindDir9am       132180 non-null object
WindDir3pm       138415 non-null object
WindSpeed9am     140845 non-null float64
WindSpeed3pm     139563 non-null float64
Humidity9am      140419 non-null float64
Humidity3pm      138583 non-null float64
Pressure9am      128179 non-null float64
Pressure3pm      128212 non-null float64
Cloud9am         88536 non-null float64
Cloud3pm         85099 non-null float64
Temp9am          141289 non-null float64
Temp3pm          139467 non-null float64
RainToday        140787 non-null object
RISK_MM          142193 non-null float64
RainTomorrow     142193 non-null object
dtypes: float64(17), object(7)
memory usage: 26.0+ MB

In [73]:
#como vemos que evaporation,sunshine, cloud9a y cloud3pm, contienen muchos dias sin informacion, no nos podemos fiar de estos campos
#por lo que hare un drop de estos ademas de fecha ya que no influye el dia que es del año porque teneoms los otros datos meteorologicos

In [74]:
dataset = dataset.drop(['Evaporation','Sunshine','Cloud9am','Cloud3pm','Date'], 1)
dataset.head()

,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,Albury,13.4,22.9,0.6,W,44.0,W,WNW,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,0.0,No
1,Albury,7.4,25.1,0.0,WNW,44.0,NNW,WSW,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,0.0,No
2,Albury,12.9,25.7,0.0,WSW,46.0,W,WSW,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No,0.0,No
3,Albury,9.2,28.0,0.0,NE,24.0,SE,E,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No,1.0,No
4,Albury,17.5,32.3,1.0,W,41.0,ENE,NW,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,0.2,No

In [75]:
#ahora eliminaremos las variables que no aportan para saber si llovera, como el nombre de la ciudad

In [76]:
dataset = dataset.drop(['Location'], 1)
dataset.head()

,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,13.4,22.9,0.6,W,44.0,W,WNW,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,0.0,No
1,7.4,25.1,0.0,WNW,44.0,NNW,WSW,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,0.0,No
2,12.9,25.7,0.0,WSW,46.0,W,WSW,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No,0.0,No
3,9.2,28.0,0.0,NE,24.0,SE,E,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No,1.0,No
4,17.5,32.3,1.0,W,41.0,ENE,NW,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,0.2,No

In [77]:
#convertiremos a variables numericas las variables

In [78]:
WindGustDir_dmy = pd.get_dummies(dataset['WindGustDir'],drop_first=True)

In [79]:
WindGustSpeed_dmy = pd.get_dummies(dataset['WindGustSpeed'],drop_first=True)

In [80]:
WindDir9am_dmy = pd.get_dummies(dataset['WindDir9am'],drop_first=True)
WindDir3pm_dmy = pd.get_dummies(dataset['WindDir3pm'],drop_first=True)
RainToday_dmy = pd.get_dummies(dataset['RainToday'],drop_first=True)
RainTomorrow_dmy= pd.get_dummies(dataset['RainTomorrow'],drop_first=True)

In [81]:
dataset.drop(['WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm', 'RainToday', 'RainTomorrow'],axis=1,inplace=True)
dataset.head()

,MinTemp,MaxTemp,Rainfall,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RISK_MM
0,13.4,22.9,0.6,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,0.0
1,7.4,25.1,0.0,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,0.0
2,12.9,25.7,0.0,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,0.0
3,9.2,28.0,0.0,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,1.0
4,17.5,32.3,1.0,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,0.2

In [82]:
dataset_dmy= pd.concat([dataset, RainTomorrow_dmy,WindGustDir_dmy,WindGustSpeed_dmy, WindDir9am_dmy ,WindDir3pm_dmy,RainToday_dmy],axis=1)

In [83]:
dataset_dmy.head()

,MinTemp,MaxTemp,Rainfall,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,...,NW,S,SE,SSE,SSW,SW,W,WNW,WSW,Yes
0,13.4,22.9,0.6,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,...,0,0,0,0,0,0,0,1,0,0
1,7.4,25.1,0.0,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,...,0,0,0,0,0,0,0,0,1,0
2,12.9,25.7,0.0,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,...,0,0,0,0,0,0,0,0,1,0
3,9.2,28.0,0.0,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,...,0,0,0,0,0,0,0,0,0,0
4,17.5,32.3,1.0,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,...,1,0,0,0,0,0,0,0,0,0

In [84]:
dataset_dmy.dropna(inplace=True)
dataset_dmy.isnull().sum()
dataset_dmy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 123968 entries, 0 to 142192
Columns: 125 entries, MinTemp to Yes
dtypes: float64(12), uint8(113)
memory usage: 25.7 MB

In [86]:
X = dataset_dmy.ix[:,(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123)].values
y = dataset_dmy.ix[:,124].values

In [87]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .3, random_state=25)
print(X_test)

[[10.3 17.7  0.  ...  0.   0.   0. ]
 [ 6.5 16.3  0.  ...  0.   0.   0. ]
 [10.6 20.6  2.8 ...  0.   0.   0. ]
 ...
 [ 8.  13.6  0.  ...  0.   0.   0. ]
 [12.2 16.7  0.  ...  0.   0.   0. ]
 [12.7 20.  11.6 ...  0.   0.   1. ]]

In [89]:
#Aprendizaje
LogReg = LogisticRegression()
LogReg.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [90]:
print("coeficientes del modelo: "+str(LogReg.coef_))
print("intercept: "+str(LogReg.intercept_))

coeficientes del modelo: [[ 1.23364488e-02  4.32900524e-02  1.28502735e+01 -6.26902241e-04
   2.45737294e-03 -9.65942484e-03  8.20184350e-03 -3.56763258e-02
   2.18856436e-02 -8.53352087e-02  2.02322251e-02 -2.84358243e-03
   3.80420552e-02  1.81999756e-01  5.14970312e-02 -4.23753147e-02
  -1.40530970e-01  4.88753157e-02  5.09293068e-02 -1.03139408e-02
  -2.63035094e-02 -7.52551894e-02 -1.17861003e-01  7.57484053e-02
  -5.97517775e-02  3.37199736e-02  1.43074192e-01 -2.25585619e-01
  -2.56232250e-04 -1.05528468e-02  1.43776624e-02 -3.76535946e-02
  -5.18157714e-02 -1.81643812e-01 -2.44393643e-02  2.35008438e-02
   1.23191368e-01  1.49259422e-01  1.30774715e-01 -5.73619992e-02
   1.45237564e-01 -7.72751071e-03 -8.49254673e-02  2.81295047e-01
  -1.27210452e-01 -8.88593222e-02 -6.10753636e-04 -1.22242372e-02
  -4.67142900e-02 -1.85862340e-01 -5.25746324e-02 -7.05809067e-02
  -1.01275874e-01  1.27187655e-01 -8.49547510e-02  2.66024957e-02
  -8.13272259e-02  3.56181246e-02  2.21104570e-02 -2.08840107e-02
   5.04616720e-02  1.00571533e-01  6.69398761e-02 -2.74901187e-02
   5.16131494e-02  7.30682575e-03 -5.72429630e-02  3.20199793e-02
   2.24829430e-02  5.40105951e-02 -1.07553274e-02 -5.11637781e-03
  -1.62694803e-02 -1.78598111e-04 -4.88359873e-04 -2.41956216e-02
   1.73741891e-02 -1.49833643e-02  3.40049161e-03  3.80738853e-02
   6.09449270e-04  1.18788419e-04 -5.86147893e-03 -7.25146483e-04
  -4.15508794e-05 -9.66196414e-04 -2.63689392e-04  1.92732596e-06
  -6.70292880e-05  0.00000000e+00 -3.35292900e-05  1.71662949e-05
   0.00000000e+00  5.60109550e-08 -1.76238998e-02 -2.24709196e-01
  -1.24328897e-01  8.04942240e-02 -1.41587361e-01  1.32295971e-02
  -7.19948368e-02  2.87549048e-03  9.53081516e-02  4.93576032e-02
   1.05885503e-01  7.42156185e-02 -8.43231320e-02 -4.60686248e-02
   8.85789543e-02 -5.94224728e-02 -1.58679542e-01  1.16097365e-01
   6.62270184e-02  6.62518444e-02 -1.87992151e-01  5.77120294e-02
   3.25940559e-02  9.82625843e-02 -2.01222921e-02 -1.28184484e-01
  -1.02768975e-01 -2.34388957e-02 -7.75700708e-02  2.20067305e-01]]
intercept: [-0.00601224]

In [91]:
y_pred = LogReg.predict(X_test)
y_pred

array([0, 0, 1, ..., 0, 0, 1], dtype=uint8)

In [92]:
#Evaluación del rendimiento del clasificador
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
confusion_matrix

array([[28867,     0],
       [    2,  8322]])

In [93]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     28867
           1       1.00      1.00      1.00      8324

   micro avg       1.00      1.00      1.00     37191
   macro avg       1.00      1.00      1.00     37191
weighted avg       1.00      1.00      1.00     37191

In [94]:
# pienso que la mejor variable predictora seria la probabilidad de lluvia del proximo dia(RISK_MM)